export const MUSCLE_GROUPS = [
  'Chest',
  'Back',
  'Shoulders',
  'Biceps',
  'Triceps',
  'Legs',
  'Glutes',
  'Core',
  'Forearms',
  'Full Body',
  'Mobility',
  'Cardio',
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export type Exercise = {
  id: string;
  name: string;
  group: MuscleGroup;
  equipment: string;
};

function make(group: MuscleGroup, items: [string, string][]): Exercise[] {
  return items.map(([name, equipment]) => ({
    id: `${group}-${name}`.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    name,
    group,
    equipment,
  }));
}

export const EXERCISES: Exercise[] = [
  ...make('Chest', [
    ['Barbell Bench Press', 'Barbell'],
    ['Incline Barbell Bench Press', 'Barbell'],
    ['Decline Bench Press', 'Barbell'],
    ['Dumbbell Bench Press', 'Dumbbell'],
    ['Incline Dumbbell Press', 'Dumbbell'],
    ['Dumbbell Fly', 'Dumbbell'],
    ['Cable Crossover', 'Cable'],
    ['Pec Deck Fly', 'Machine'],
    ['Chest Press Machine', 'Machine'],
    ['Push-Up', 'Bodyweight'],
    ['Chest Dip', 'Bodyweight'],
    ['Smith Machine Bench Press', 'Machine'],
    ['Low Cable Fly', 'Cable'],
    ['High Cable Fly', 'Cable'],
    ['Incline Push-Up', 'Bodyweight'],
    ['Decline Push-Up', 'Bodyweight'],
    ['Landmine Press', 'Barbell'],
    ['Svend Press', 'Plate'],
    ['Incline Machine Press', 'Machine'],
    ['Guillotine Press', 'Barbell'],
    ['Dumbbell Squeeze Press', 'Dumbbell'],
    ['Incline Dumbbell Fly', 'Dumbbell'],
    ['Decline Dumbbell Press', 'Dumbbell'],
    ['Cable Chest Press', 'Cable'],
    ['Machine Fly', 'Machine'],
    ['Weighted Push-Up', 'Bodyweight'],
    ['Ring Push-Up', 'Rings'],
    ['Archer Push-Up', 'Bodyweight'],
    ['Plyometric Push-Up', 'Bodyweight'],
  ]),
  ...make('Back', [
    ['Deadlift', 'Barbell'],
    ['Barbell Row', 'Barbell'],
    ['Pendlay Row', 'Barbell'],
    ['Pull-Up', 'Bodyweight'],
    ['Chin-Up', 'Bodyweight'],
    ['Lat Pulldown', 'Cable'],
    ['Seated Cable Row', 'Cable'],
    ['One-Arm Dumbbell Row', 'Dumbbell'],
    ['T-Bar Row', 'Barbell'],
    ['Straight-Arm Pulldown', 'Cable'],
    ['Back Extension', 'Bodyweight'],
    ['Machine Row', 'Machine'],
    ['Rack Pull', 'Barbell'],
    ['Single-Arm Lat Pulldown', 'Cable'],
    ['Wide-Grip Seated Row', 'Cable'],
    ['Inverted Row', 'Bodyweight'],
    ['Chest-Supported Dumbbell Row', 'Dumbbell'],
    ['Meadows Row', 'Barbell'],
    ['Neutral-Grip Pull-Up', 'Bodyweight'],
    ['Dumbbell Pullover', 'Dumbbell'],
    ['Good Morning', 'Barbell'],
    ['Reverse Hyperextension', 'Machine'],
    ['Seal Row', 'Barbell'],
    ['Single-Arm Cable Row', 'Cable'],
    ['High Row Machine', 'Machine'],
    ['Weighted Pull-Up', 'Bodyweight'],
    ['Assisted Pull-Up', 'Machine'],
    ['Close-Grip Lat Pulldown', 'Cable'],
    ['Reverse-Grip Lat Pulldown', 'Cable'],
    ['Dumbbell Deadlift', 'Dumbbell'],
    ['Trap Bar Deadlift', 'Trap bar'],
    ['Dumbbell Renegade Row', 'Dumbbell'],
    ['Kroc Row', 'Dumbbell'],
    ['Superman', 'Bodyweight'],
  ]),
  ...make('Shoulders', [
    ['Overhead Press', 'Barbell'],
    ['Seated Dumbbell Press', 'Dumbbell'],
    ['Arnold Press', 'Dumbbell'],
    ['Lateral Raise', 'Dumbbell'],
    ['Front Raise', 'Dumbbell'],
    ['Rear Delt Fly', 'Dumbbell'],
    ['Face Pull', 'Cable'],
    ['Upright Row', 'Barbell'],
    ['Barbell Shrug', 'Barbell'],
    ['Shoulder Press Machine', 'Machine'],
    ['Cable Lateral Raise', 'Cable'],
    ['Machine Lateral Raise', 'Machine'],
    ['Reverse Pec Deck', 'Machine'],
    ['Push Press', 'Barbell'],
    ['Landmine Shoulder Press', 'Barbell'],
    ['Dumbbell Shrug', 'Dumbbell'],
    ['Pike Push-Up', 'Bodyweight'],
    ['Behind-the-Neck Press', 'Barbell'],
    ['Bent-Over Lateral Raise', 'Dumbbell'],
    ['Cuban Press', 'Dumbbell'],
    ['Z Press', 'Barbell'],
    ['Cable Front Raise', 'Cable'],
    ['Plate Front Raise', 'Plate'],
    ['Dumbbell Y Raise', 'Dumbbell'],
    ['Cable Face Pull to Chin', 'Cable'],
    ['Handstand Push-Up', 'Bodyweight'],
    ['Machine Shrug', 'Machine'],
    ['Cable Rear Delt Fly', 'Cable'],
    ['Lu Raise', 'Dumbbell'],
  ]),
  ...make('Biceps', [
    ['Barbell Curl', 'Barbell'],
    ['Dumbbell Curl', 'Dumbbell'],
    ['Hammer Curl', 'Dumbbell'],
    ['Preacher Curl', 'Barbell'],
    ['Incline Dumbbell Curl', 'Dumbbell'],
    ['Cable Curl', 'Cable'],
    ['Concentration Curl', 'Dumbbell'],
    ['EZ-Bar Curl', 'Barbell'],
    ['Spider Curl', 'Dumbbell'],
    ['Reverse Curl', 'Barbell'],
    ['Cross-Body Hammer Curl', 'Dumbbell'],
    ['Machine Preacher Curl', 'Machine'],
    ['Bayesian Cable Curl', 'Cable'],
    ['Zottman Curl', 'Dumbbell'],
    ['Drag Curl', 'Barbell'],
    ['Waiter Curl', 'Dumbbell'],
    ['High Cable Curl', 'Cable'],
    ['Seated Dumbbell Curl', 'Dumbbell'],
    ['Chin-Up Hold', 'Bodyweight'],
    ['21s Barbell Curl', 'Barbell'],
    ['Single-Arm Preacher Curl', 'Dumbbell'],
    ['Band Curl', 'Band'],
  ]),
  ...make('Triceps', [
    ['Close-Grip Bench Press', 'Barbell'],
    ['Triceps Pushdown', 'Cable'],
    ['Overhead Triceps Extension', 'Dumbbell'],
    ['Skull Crusher', 'Barbell'],
    ['Triceps Dip', 'Bodyweight'],
    ['Cable Rope Overhead Extension', 'Cable'],
    ['Triceps Kickback', 'Dumbbell'],
    ['Diamond Push-Up', 'Bodyweight'],
    ['JM Press', 'Barbell'],
    ['Single-Arm Cable Pushdown', 'Cable'],
    ['Bench Dip', 'Bodyweight'],
    ['Machine Triceps Extension', 'Machine'],
    ['Cable Overhead Extension', 'Cable'],
    ['Floor Press', 'Barbell'],
    ['Tate Press', 'Dumbbell'],
    ['Rope Pushdown', 'Cable'],
    ['Reverse-Grip Pushdown', 'Cable'],
    ['Incline Skull Crusher', 'Barbell'],
    ['Dumbbell Skull Crusher', 'Dumbbell'],
    ['Parallel Bar Dip', 'Bodyweight'],
    ['Weighted Dip', 'Bodyweight'],
    ['Band Pushdown', 'Band'],
  ]),
  ...make('Legs', [
    ['Barbell Back Squat', 'Barbell'],
    ['Front Squat', 'Barbell'],
    ['Leg Press', 'Machine'],
    ['Hack Squat', 'Machine'],
    ['Romanian Deadlift', 'Barbell'],
    ['Walking Lunge', 'Dumbbell'],
    ['Bulgarian Split Squat', 'Dumbbell'],
    ['Goblet Squat', 'Kettlebell'],
    ['Leg Extension', 'Machine'],
    ['Lying Leg Curl', 'Machine'],
    ['Standing Calf Raise', 'Machine'],
    ['Seated Calf Raise', 'Machine'],
    ['Box Squat', 'Barbell'],
    ['Sissy Squat', 'Bodyweight'],
    ['Smith Machine Squat', 'Machine'],
    ['Reverse Lunge', 'Dumbbell'],
    ['Lateral Lunge', 'Dumbbell'],
    ['Stiff-Leg Deadlift', 'Barbell'],
    ['Seated Leg Curl', 'Machine'],
    ['Nordic Hamstring Curl', 'Bodyweight'],
    ['Hip Adduction Machine', 'Machine'],
    ['Donkey Calf Raise', 'Machine'],
    ['Leg Press Calf Raise', 'Machine'],
    ['Wall Sit', 'Bodyweight'],
    ['Box Jump', 'Plyo box'],
    ['Pistol Squat', 'Bodyweight'],
    ['Zercher Squat', 'Barbell'],
    ['Overhead Squat', 'Barbell'],
    ['Belt Squat', 'Machine'],
    ['Pendulum Squat', 'Machine'],
    ['Leg Press Single Leg', 'Machine'],
    ['Dumbbell Romanian Deadlift', 'Dumbbell'],
    ['Single-Leg Romanian Deadlift', 'Dumbbell'],
    ['Deficit Reverse Lunge', 'Dumbbell'],
    ['Barbell Lunge', 'Barbell'],
    ['Cossack Squat', 'Bodyweight'],
    ['Jump Squat', 'Bodyweight'],
    ['Standing Leg Curl', 'Machine'],
    ['Tibialis Raise', 'Bodyweight'],
    ['Single-Leg Calf Raise', 'Bodyweight'],
    ['Sled Leg Press', 'Sled'],
    ['Spanish Squat', 'Band'],
  ]),
  ...make('Glutes', [
    ['Hip Thrust', 'Barbell'],
    ['Glute Bridge', 'Bodyweight'],
    ['Cable Kickback', 'Cable'],
    ['Sumo Deadlift', 'Barbell'],
    ['Step-Up', 'Dumbbell'],
    ['Hip Abduction Machine', 'Machine'],
    ['Kettlebell Swing', 'Kettlebell'],
    ['Single-Leg Hip Thrust', 'Bodyweight'],
    ['Frog Pump', 'Bodyweight'],
    ['Fire Hydrant', 'Bodyweight'],
    ['Cable Pull-Through', 'Cable'],
    ['Banded Lateral Walk', 'Band'],
    ['Curtsy Lunge', 'Dumbbell'],
    ['Smith Machine Hip Thrust', 'Machine'],
    ['Donkey Kick', 'Bodyweight'],
    ['Barbell Glute Bridge', 'Barbell'],
    ['Cable Hip Abduction', 'Cable'],
    ['Reverse Hyperextension Glute Focus', 'Machine'],
    ['Bulgarian Split Squat Glute Focus', 'Dumbbell'],
    ['Lateral Band Step', 'Band'],
    ['Hip Thrust Machine', 'Machine'],
    ['Kneeling Cable Kickback', 'Cable'],
    ['Seated Banded Abduction', 'Band'],
  ]),
  ...make('Core', [
    ['Plank', 'Bodyweight'],
    ['Crunch', 'Bodyweight'],
    ['Hanging Leg Raise', 'Bodyweight'],
    ['Cable Crunch', 'Cable'],
    ['Russian Twist', 'Bodyweight'],
    ['Ab Wheel Rollout', 'Ab wheel'],
    ['Bicycle Crunch', 'Bodyweight'],
    ['Mountain Climber', 'Bodyweight'],
    ['Side Plank', 'Bodyweight'],
    ['Dead Bug', 'Bodyweight'],
    ['Bird Dog', 'Bodyweight'],
    ['Hollow Hold', 'Bodyweight'],
    ['V-Up', 'Bodyweight'],
    ['Pallof Press', 'Cable'],
    ['Woodchopper', 'Cable'],
    ['Decline Sit-Up', 'Bodyweight'],
    ['Toes to Bar', 'Bodyweight'],
    ['Dragon Flag', 'Bodyweight'],
    ['Flutter Kick', 'Bodyweight'],
    ['Suitcase Carry', 'Dumbbell'],
    ['Cable Side Bend', 'Cable'],
    ['Weighted Sit-Up', 'Plate'],
    ['Landmine Rotation', 'Barbell'],
    ['Stir the Pot', 'Stability ball'],
    ['Reverse Crunch', 'Bodyweight'],
    ['Leg Raise', 'Bodyweight'],
    ["Captain's Chair Knee Raise", 'Machine'],
    ['Copenhagen Plank', 'Bodyweight'],
    ['Body Saw', 'Sliders'],
    ['Plank Shoulder Tap', 'Bodyweight'],
    ['Heel Touch', 'Bodyweight'],
    ['Ab Crunch Machine', 'Machine'],
  ]),
  ...make('Forearms', [
    ['Wrist Curl', 'Barbell'],
    ['Reverse Wrist Curl', 'Barbell'],
    ["Farmer's Walk", 'Dumbbell'],
    ['Plate Pinch', 'Plate'],
    ['Dead Hang', 'Bodyweight'],
    ['Wrist Roller', 'Wrist roller'],
    ['Behind-the-Back Wrist Curl', 'Barbell'],
    ['Gripper Squeeze', 'Gripper'],
    ['Fat Grip Hold', 'Barbell'],
    ['Towel Pull-Up', 'Bodyweight'],
    ['Hammer Wrist Raise', 'Dumbbell'],
  ]),
  ...make('Full Body', [
    ['Clean and Press', 'Barbell'],
    ['Power Clean', 'Barbell'],
    ['Snatch', 'Barbell'],
    ['Thruster', 'Barbell'],
    ['Kettlebell Clean and Press', 'Kettlebell'],
    ['Turkish Get-Up', 'Kettlebell'],
    ['Man Maker', 'Dumbbell'],
    ['Sandbag Carry', 'Sandbag'],
    ['Medicine Ball Slam', 'Medicine ball'],
    ['Bear Crawl', 'Bodyweight'],
    ['Hang Clean', 'Barbell'],
    ['Hang Snatch', 'Barbell'],
    ['Clean and Jerk', 'Barbell'],
    ['Dumbbell Snatch', 'Dumbbell'],
    ['Dumbbell Thruster', 'Dumbbell'],
    ['Kettlebell Snatch', 'Kettlebell'],
    ['Sled Drag', 'Sled'],
    ['Tire Flip', 'Tire'],
    ['Wall Ball', 'Medicine ball'],
    ['Burpee Pull-Up', 'Bodyweight'],
    ['Devil Press', 'Dumbbell'],
    ['Inchworm', 'Bodyweight'],
  ]),
  ...make('Mobility', [
    ["Cat-Cow", 'Bodyweight'],
    ["World's Greatest Stretch", 'Bodyweight'],
    ['Hip Flexor Stretch', 'Bodyweight'],
    ['Hamstring Stretch', 'Bodyweight'],
    ['Pigeon Pose', 'Bodyweight'],
    ["Child's Pose", 'Bodyweight'],
    ['Downward Dog', 'Bodyweight'],
    ['Thoracic Spine Rotation', 'Bodyweight'],
    ['Shoulder Dislocates', 'Band'],
    ['Band Pull-Apart', 'Band'],
    ['90/90 Hip Switch', 'Bodyweight'],
    ['Couch Stretch', 'Bodyweight'],
    ['Foam Rolling', 'Foam roller'],
    ['Doorway Chest Stretch', 'Bodyweight'],
    ['Ankle Mobility Drill', 'Bodyweight'],
    ['Quad Stretch', 'Bodyweight'],
    ['Yoga Flow', 'Bodyweight'],
    ['Dynamic Warm-Up', 'Bodyweight'],
  ]),
  ...make('Cardio', [
    ['Treadmill Run', 'Cardio machine'],
    ['Stationary Bike', 'Cardio machine'],
    ['Rowing Machine', 'Cardio machine'],
    ['Elliptical', 'Cardio machine'],
    ['Stair Climber', 'Cardio machine'],
    ['Jump Rope', 'Rope'],
    ['Battle Ropes', 'Rope'],
    ['Outdoor Run', 'None'],
    ['Swimming', 'Pool'],
    ['Assault Bike', 'Cardio machine'],
    ['Ski Erg', 'Cardio machine'],
    ['Incline Treadmill Walk', 'Cardio machine'],
    ['Jumping Jacks', 'Bodyweight'],
    ['Burpees', 'Bodyweight'],
    ['High Knees', 'Bodyweight'],
    ['Sled Push', 'Sled'],
    ['Cycling Outdoors', 'Bike'],
    ['Hiking', 'None'],
    ['HIIT Circuit', 'Bodyweight'],
    ['Sprint Intervals', 'None'],
    ['Hill Sprints', 'None'],
    ['Spin Class', 'Cardio machine'],
    ['Cross Trainer', 'Cardio machine'],
    ['Versaclimber', 'Cardio machine'],
    ['Shadow Boxing', 'None'],
    ['Heavy Bag Work', 'Heavy bag'],
    ['Skater Jumps', 'Bodyweight'],
    ['Tuck Jumps', 'Bodyweight'],
    ['Stair Running', 'None'],
    ['Aqua Jogging', 'Pool'],
    ['Dance Cardio', 'None'],
  ]),
];

export function exerciseById(id: string) {
  return EXERCISES.find((exercise) => exercise.id === id) ?? null;
}
